### ISSUE TITLE
Does Cocos2d-Mono have extension on Visual Studio marketplace

### ISSUE THREAD

**Issue by moon672** [brandmooffin/cocos2d-mono#38]
Hi there.

I recently came across to this project and I am really interested to it. I have seen an template extension on Visual studio marketplace published by "Cocos2D-Mono Team and Broker". So I just want to know, is this extension the official project template extension?

**Comment by brandmooffin** [comment]
Thanks for your interest in the project! Yes, I can confirm that it is the official extension. Please feel free to check it out! I'm also working on updating the documentation here, which should be up in the next day or so.

**Comment by moon672** [comment]
Thank You very much for the good work. I am very much interested in this project. Would you please like to share anything and how can I contribute in this project? Thank you very much...

**Comment by brandmooffin** [comment]
@moon672 if you'd like to contribute, feel free to fork this repo and make any changes you'd like and then open a pull request against this repo and we can look at getting any changes you make into this project.
