### ISSUE TITLE
Keyboard is not working in the Box2dTestBed(Box2D) sample

### ISSUE THREAD

**Issue by womandroid** [brandmooffin/cocos2d-mono#39]
When running this sample,  the keyboard does not work. I noticed that Box2DView uses the code `KeyboardEnabled = true` and override the `KeyPressed(Keys key)` function, but it didn't work, the `KeyPressed` has never been called.

**Comment by brandmooffin** [comment]
Thanks for discovering this issue! I will investigate this and get back to you here once I have a fix 😄

**Comment by brandmooffin** [comment]
So I was able to reproduce the issue and I can see it's affects all the other tests as well. I have opened a new issue to track the changes #41 and I will also update this issue once I have a fix in place

**Comment by brandmooffin** [comment]
A fix was merged into master to address this issue. Let me know if you are still running into the issue.
