### ISSUE TITLE
Is PSVita support coming?

### ISSUE THREAD

**Issue by BurAndBY** [brandmooffin/cocos2d-mono#70]
The project's readme hasn't been updated in awhile.

**Comment by brandmooffin** [comment]
Hey @BurAndBY ! Sorry about the really delayed reply here, lots going on!

The readme is actually pretty dated unfortunately, I'm planning on revamping that as there are quite a few changes I have coming very soon. As for PSVita support, it is being moved to unofficially support/deprecated.

As Sony has moved to close up the shop and support for Vita and MonoGame has moved away from supporting the platform, it makes sense to do the same as the platform is essentially deprecated.

That said, if you still have access to the Sony provided Vita SDK, it is possible to take [2.3.7](https://github.com/brandmooffin/cocos2d-mono/releases/tag/2.3.7) and using MonoGame 3.7.1 to develop games for the PSVita. Though I don't know what the current status is on hardware to test with.

Hope that's helpful and feel free to reach out with any other questions!

**Comment by BurAndBY** [comment]
> Hey @BurAndBY ! Sorry about the really delayed reply here, lots going on!
> 
> The readme is actually pretty dated unfortunately, I'm planning on revamping that as there are quite a few changes I have coming very soon. As for PSVita support, it is being moved to unofficially support/deprecated.
> 
> As Sony has moved to close up the shop and support for Vita and MonoGame has moved away from supporting the platform, it makes sense to do the same as the platform is essentially deprecated.
> 
> That said, if you still have access to the Sony provided Vita SDK, it is possible to take [2.3.7](https://github.com/brandmooffin/cocos2d-mono/releases/tag/2.3.7) and using MonoGame 3.7.1 to develop games for the PSVita. Though I don't know what the current status is on hardware to test with.
> 
> Hope that's helpful and feel free to reach out with any other questions!

Well, sad to hear that. I will test that version.

**Comment by BurAndBY** [comment]
Also, about the SDK. It's now in the web and easily downloadable.
